<?php

/**
 * BaseClienteArchivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre_archivo
 * @property timestamp $fecha_subida
 * @property integer $cantidad_datos
 * @property Doctrine_Collection $Cliente
 * 
 * @method string              getNombreArchivo()  Returns the current record's "nombre_archivo" value
 * @method timestamp           getFechaSubida()    Returns the current record's "fecha_subida" value
 * @method integer             getCantidadDatos()  Returns the current record's "cantidad_datos" value
 * @method Doctrine_Collection getCliente()        Returns the current record's "Cliente" collection
 * @method ClienteArchivo      setNombreArchivo()  Sets the current record's "nombre_archivo" value
 * @method ClienteArchivo      setFechaSubida()    Sets the current record's "fecha_subida" value
 * @method ClienteArchivo      setCantidadDatos()  Sets the current record's "cantidad_datos" value
 * @method ClienteArchivo      setCliente()        Sets the current record's "Cliente" collection
 * 
 * @package    tramimundo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClienteArchivo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cliente_archivo');
        $this->hasColumn('nombre_archivo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fecha_subida', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('cantidad_datos', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cliente', array(
             'local' => 'id',
             'foreign' => 'archivo_id'));
    }
}