<?php

/**
 * BaseCliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $archivo_id
 * @property string $billing_document
 * @property string $no_parte
 * @property string $descripcion
 * @property string $fraccion
 * @property string $uc
 * @property string $cantidad
 * @property double $valor
 * @property string $origen
 * @property double $peso
 * @property ClienteArchivo $ClienteArchivo
 * 
 * @method integer        getArchivoId()        Returns the current record's "archivo_id" value
 * @method string         getBillingDocument()  Returns the current record's "billing_document" value
 * @method string         getNoParte()          Returns the current record's "no_parte" value
 * @method string         getDescripcion()      Returns the current record's "descripcion" value
 * @method string         getFraccion()         Returns the current record's "fraccion" value
 * @method string         getUc()               Returns the current record's "uc" value
 * @method string         getCantidad()         Returns the current record's "cantidad" value
 * @method double         getValor()            Returns the current record's "valor" value
 * @method string         getOrigen()           Returns the current record's "origen" value
 * @method double         getPeso()             Returns the current record's "peso" value
 * @method ClienteArchivo getClienteArchivo()   Returns the current record's "ClienteArchivo" value
 * @method Cliente        setArchivoId()        Sets the current record's "archivo_id" value
 * @method Cliente        setBillingDocument()  Sets the current record's "billing_document" value
 * @method Cliente        setNoParte()          Sets the current record's "no_parte" value
 * @method Cliente        setDescripcion()      Sets the current record's "descripcion" value
 * @method Cliente        setFraccion()         Sets the current record's "fraccion" value
 * @method Cliente        setUc()               Sets the current record's "uc" value
 * @method Cliente        setCantidad()         Sets the current record's "cantidad" value
 * @method Cliente        setValor()            Sets the current record's "valor" value
 * @method Cliente        setOrigen()           Sets the current record's "origen" value
 * @method Cliente        setPeso()             Sets the current record's "peso" value
 * @method Cliente        setClienteArchivo()   Sets the current record's "ClienteArchivo" value
 * 
 * @package    tramimundo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCliente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cliente');
        $this->hasColumn('archivo_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('billing_document', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('no_parte', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fraccion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('uc', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cantidad', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('valor', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('origen', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('peso', 'double', null, array(
             'type' => 'double',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClienteArchivo', array(
             'local' => 'archivo_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}