<?php

/**
 * BaseBaseDatosArchivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre_archivo
 * @property timestamp $fecha_subida
 * @property integer $cantidad_datos
 * @property Doctrine_Collection $BaseDatos
 * 
 * @method string              getNombreArchivo()  Returns the current record's "nombre_archivo" value
 * @method timestamp           getFechaSubida()    Returns the current record's "fecha_subida" value
 * @method integer             getCantidadDatos()  Returns the current record's "cantidad_datos" value
 * @method Doctrine_Collection getBaseDatos()      Returns the current record's "BaseDatos" collection
 * @method BaseDatosArchivo    setNombreArchivo()  Sets the current record's "nombre_archivo" value
 * @method BaseDatosArchivo    setFechaSubida()    Sets the current record's "fecha_subida" value
 * @method BaseDatosArchivo    setCantidadDatos()  Sets the current record's "cantidad_datos" value
 * @method BaseDatosArchivo    setBaseDatos()      Sets the current record's "BaseDatos" collection
 * 
 * @package    tramimundo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBaseDatosArchivo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('base_datos_archivo');
        $this->hasColumn('nombre_archivo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fecha_subida', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('cantidad_datos', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BaseDatos', array(
             'local' => 'id',
             'foreign' => 'archivo_id'));
    }
}