<?php

/**
 * BaseDatosArchivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BaseDatosArchivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BaseDatosArchivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BaseDatosArchivo');
    }
}