generator:
  class: sfDoctrineGenerator
  param:
    model_class:           BaseDatos
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          base_datos
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Base de Datos Tramimundo
        display: [BaseDatosArchivo, no_parte, descripcion, fraccion, arancel, uc, cantidad, valor, origen]
      filter:
        display: [archivo_id, no_parte, uc]
      form:    ~
      edit:
        title: Editar
      new:
        title: Crear
